name: "Omochice/action-normalized-vim-plugin-name"
description: "Provide normalized vim plugin name"
author: "Omochice"

# Metadata for market place
branding:
  icon: "activity"
  color: "blue"

# Define your inputs here.
inputs:
  trim-tail-dot-vim:
    description: "Whether trim tail '.vim' pattern"
    required: false
    default: "false"

# Define your outputs here.
outputs:
  normalizedName:
    description: 'Normalized plugin name'
    value: ${{ steps.name.outputs.normalizedName }}

runs:
  using: composite
  steps:
    - uses: denoland/setup-deno@v2
    - id: name
      run:
        deno run
        --allow-env=NODE_V8_COVERAGE,JEST_WORKER_ID,GITHUB_EVENT_PATH,GITHUB_EVENT_NAME,GITHUB_SHA,GITHUB_REF,GITHUB_WORKFLOW,GITHUB_ACTION,GITHUB_ACTOR,GITHUB_JOB,GITHUB_RUN_NUMBER,GITHUB_RUN_ID,GITHUB_SERVER_URL,GITHUB_GRAPHQL_URL,no_proxy,NO_PROXY,https_proxy,HTTPS_PROXY
        src/main.ts
        ${{ inputs.trim-tail-dot-vim == 'true' && '--trim-tail-dot-vim' || '' }} ${{ github.repository }}
      shell: bash
