name: "Omochice/action-normalized-vim-plugin-name"
description: "Provide normalized vim plugin name"
author: "Omochice"

# Metadata for market place
branding:
  icon: "activity"
  color: "blue"

# Define your inputs here.
inputs:
  trim-tail-dot-vim:
    description: "Whether trim tail '.vim' pattern"
    required: false
    default: "false"

# Define your outputs here.
outputs:
  normalizedName:
    description: 'Normalized plugin name'
    value: ${{ steps.name.normalizedName }}

runs:
  using: composite
  steps:
    - uses: denoland/setup-deno@v2
    - id: name
      run: deno run --allow-all src/main.ts
      shell: bash
