name: CI

on:
  push: null
  pull_request: null
  workflow_dispatch: null
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./
        id: normalize
      - run: echo "${{ steps.normalize.outputs.normalizedName }}"
